# by weilan in 2020.01.25 

services:
  # 主应用配置
  master:
    container_name: master
    restart: always
    build: 
      context: ./master
      dockerfile: Dockerfile
    environment:
      NODE_ENV: 'production'
    ports:
      - '2750:2750'
  # subapp-blog配置
  blog:
    container_name: subapp-blog
    restart: always
    build: 
      context: ./subapp-blog
      dockerfile: Dockerfile
    environment:
      NODE_ENV: 'production'
    ports:
      - '2752:2752'
    depends_on:
      - master
  # subapp-login配置
  login:
    container_name: subapp-login
    restart: always
    build: 
      context: ./subapp-login
      dockerfile: Dockerfile
    environment:
      NODE_ENV: 'production'
    ports:
      - '2753:2753'
    depends_on:
      - master
  # subapp-ui配置
  ui:
    container_name: subapp-ui
    restart: always
    build: 
      context: ./subapp-ui
      dockerfile: Dockerfile
    environment:
      NODE_ENV: 'production'
    ports:
      - '2751:2751'
    depends_on:
      - master